version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: bizpulse
      POSTGRES_PASSWORD: bizpulse123
      POSTGRES_DB: bizpulse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: